-- liquibase formatted sql

--changeset iaktov:1
CREATE TABLE Users
(
    email     TEXT,
    first_name TEXT,
    id        bigint primary key,
    last_name  TEXT,
    phone     TEXT,
    reg_date   TEXT,
    city      TEXT

);

CREATE TABLE Ads
(
    pk     bigint generated by default as identity primary key,
    price  BIGINT,
    title  TEXT,
    description text,
    user_id bigint references Users (id) on delete cascade

);

CREATE TABLE Comments
(

    created_at TEXT,
    pk         integer generated by default as identity primary key,
    text       TEXT,
    user_id  bigint REFERENCES Users (id) ON DELETE CASCADE,
    ads_pk bigint REFERENCES Ads (pk) ON DELETE CASCADE
);


create table Images
(
    file_size  bigint,
    media_type varchar(255),
    image     bytea,
    id        bigint generated by default as identity primary key,
    ads_pk bigint  REFERENCES Ads (pk) ON DELETE CASCADE
);

--changeset anmalashenko:3
alter table Users add column enabled boolean;
create sequence users_id_seq;
alter table Users alter column id set default nextval('users_id_seq');
alter sequence users_id_seq OWNED BY Users.id;

create table if not exists authorities (
                                           username  varchar(255) not null primary key,
                                           authority varchar(32)
);
